services:
  signpost:
    container_name: SignPost
    image: ghcr.io/jfberry/signpost:latest
    ports:
      - "3035:3035"
    volumes:
      - ./config.toml:/usr/src/app/config.toml
    restart: unless-stopped